//
//  vv_motivation_circuit.cpp
//  chatbot1
//
//  Created by Benjamin Y Chan on 2/4/16.
//  Copyright © 2016 vervious. All rights reserved.
//

#include "vv_motivation_circuit.hpp"

void MotivationCircuit::someFunctionThatNeedsSpecification() {
    // so, first
    /**
     *    2) an information closeness measure:
     *          - unlabeled, faced with the unknown
     *       a) First, generate a prediction. Or rather, an expectation, in the realm that would have most utility.
     *       b) Second, generate an action that would test that prediction.
     *       c) Finally, derive information closeness based on the results of that prediction.
     *
     *    Revision: 2) information gain given an action
     *          - goal: pick the action with the most information gain (short term or long term?)...
     *          - how do we deal with picking actions? There is an infinite set of actions to pick from...
     *          - should actions be generated by the information nexus? Perhaps we should include them in the
     *              idea of information.
     *       a) Given an action, predict its "information gain"
     *          - the amount of action per symbol, or internal composition, should perhaps also be stored in the knowledge nexus
     *          - hmmm this is a little hard to quantify
     **/
}